version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lostfound_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: lostfounddb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lostfounddb"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: lostfound_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update